version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: checker
    container_name: checker-app
    command: /start
    volumes:
      - ./checker:/code/checker
    ports:
      - "${APP_EXTERNAL_PORT}:5000"
    networks:
      - nginx_network

  app-nginx:
    image: 'nginx:1.17'
    container_name: checker-nginx
    volumes:
      - './compose/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - 'app'
    ports:
      - "${NGINX_EXTERNAL_PORT}:8000"
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge